### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Neutralas** [SkyPedal/SkyPedal#4]
- [ ] #1 Wireframe for the home page
- [ ] #2 Login/Logout button in the home page
- [ ] #5 Button for manually uploading data
